import type { ReactNode } from "react";
import "../css/vars.css";
import "../css/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Theme from "@/theme";
import { KumaRegistry } from "@kuma-ui/next-plugin/registry";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: ReactNode;
};

const RootLayout = (props: Props) => {
  const { children } = props;

  return (
    <KumaRegistry>
      <html lang="en">
        <body className={inter.className}>
          {children}
          <Theme.setup />
        </body>
      </html>
    </KumaRegistry>
  );
};

export default RootLayout;
